[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[vars]
url = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
database__connection__ssl = "true"
