# Redeploy trigger: 2026-01-16 13:04
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[vars]
database__client = "mysql"
database__connection__host = "${{MYSQLHOST}}"
database__connection__user = "${{MYSQLUSER}}"
database__connection__password = "${{MYSQLPASSWORD}}"
database__connection__database = "${{MYSQLDATABASE}}"
database__connection__port = "${{MYSQLPORT}}"
